project_id = "ohuyedvawwocflnybrkl"

[functions.extract-dau-data]
verify_jwt = false

[functions.extract-lab-results]
verify_jwt = false

[functions.classify-and-extract]
verify_jwt = false

[functions.generate-embeddings]
verify_jwt = false

[functions.semantic-search]
verify_jwt = false

[functions.clinical-assistant]
verify_jwt = false

[functions.analyze-patterns]
verify_jwt = false