[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
