-- Expansión de códigos CIE-10 para Pediatría
-- Fecha: 2025-01-09
-- Incluye diagnósticos pediátricos comunes que faltaban

-- Insertar códigos CIE-10 pediátricos
INSERT INTO cie10_codes (code, description, category) VALUES

-- ENFERMEDADES RESPIRATORIAS
('J21.0', 'Bronquiolitis aguda debida a virus sincicial respiratorio', 'Respiratorio'),
('J21.8', 'Bronquiolitis aguda debida a otros microorganismos especificados', 'Respiratorio'),
('J21.9', 'Bronquiolitis aguda, no especificada', 'Respiratorio'),
('J20.9', 'Bronquitis aguda, no especificada', 'Respiratorio'),
('J20.0', 'Bronquitis aguda debida a Mycoplasma pneumoniae', 'Respiratorio'),
('J45.0', 'Asma predominantemente alérgica', 'Respiratorio'),
('J45.1', 'Asma no alérgica', 'Respiratorio'),
('J45.8', 'Asma mixta', 'Respiratorio'),
('J45.9', 'Asma, no especificada', 'Respiratorio'),
('J44.0', 'Enfermedad pulmonar obstructiva crónica con infección respiratoria aguda del tracto inferior', 'Respiratorio'),
('J44.1', 'Enfermedad pulmonar obstructiva crónica con exacerbación aguda, no especificada', 'Respiratorio'),
('J18.9', 'Neumonía, no especificada', 'Respiratorio'),
('J18.0', 'Bronconeumonía, no especificada', 'Respiratorio'),
('J18.1', 'Neumonía lobar, no especificada', 'Respiratorio'),
('J12.0', 'Neumonía debida a adenovirus', 'Respiratorio'),
('J12.1', 'Neumonía debida a virus sincicial respiratorio', 'Respiratorio'),
('J13', 'Neumonía debida a Streptococcus pneumoniae', 'Respiratorio'),
('J15.0', 'Neumonía debida a Klebsiella pneumoniae', 'Respiratorio'),
('J15.1', 'Neumonía debida a Pseudomonas', 'Respiratorio'),
('J15.7', 'Neumonía debida a Mycoplasma pneumoniae', 'Respiratorio'),
('J06.9', 'Infección aguda de las vías respiratorias superiores, no especificada', 'Respiratorio'),
('J02.9', 'Faringitis aguda, no especificada', 'Respiratorio'),
('J03.9', 'Amigdalitis aguda, no especificada', 'Respiratorio'),
('J00', 'Rinofaringitis aguda (resfriado común)', 'Respiratorio'),
('J04.0', 'Laringitis aguda', 'Respiratorio'),
('J04.1', 'Traqueítis aguda', 'Respiratorio'),
('J04.2', 'Laringotraqueítis aguda', 'Respiratorio'),
('J05.0', 'Laringitis obstructiva aguda (crup)', 'Respiratorio'),
('J05.1', 'Epiglotitis aguda', 'Respiratorio'),
('J22', 'Infección aguda no especificada de las vías respiratorias inferiores', 'Respiratorio'),
('J96.0', 'Insuficiencia respiratoria aguda', 'Respiratorio'),
('J96.9', 'Insuficiencia respiratoria, no especificada', 'Respiratorio'),

-- ENFERMEDADES INFECCIOSAS
('A09', 'Diarrea y gastroenteritis de presunto origen infeccioso', 'Infeccioso'),
('A08.0', 'Enteritis debida a rotavirus', 'Infeccioso'),
('A08.1', 'Gastroenteritis aguda debida a agente de Norwalk', 'Infeccioso'),
('A08.2', 'Enteritis debida a adenovirus', 'Infeccioso'),
('A08.4', 'Infección intestinal viral, no especificada', 'Infeccioso'),
('A09.0', 'Otras gastroenteritis y colitis de origen infeccioso y no especificado', 'Infeccioso'),
('A09.9', 'Gastroenteritis y colitis de origen no especificado', 'Infeccioso'),
('A41.9', 'Septicemia, no especificada', 'Infeccioso'),
('A41.0', 'Septicemia debida a Staphylococcus aureus', 'Infeccioso'),
('A41.1', 'Septicemia debida a otros estafilococos especificados', 'Infeccioso'),
('A41.5', 'Septicemia debida a otros microorganismos gramnegativos', 'Infeccioso'),
('R57.2', 'Shock séptico', 'Infeccioso'),
('A49.9', 'Infección bacteriana, no especificada', 'Infeccioso'),
('B34.9', 'Infección viral, no especificada', 'Infeccioso'),
('B00.9', 'Infección debida a virus del herpes, no especificada', 'Infeccioso'),
('B01.9', 'Varicela sin complicación', 'Infeccioso'),
('B05.9', 'Sarampión sin complicación', 'Infeccioso'),
('B06.9', 'Rubéola sin complicación', 'Infeccioso'),
('B26.9', 'Parotiditis sin complicación', 'Infeccioso'),
('B27.9', 'Mononucleosis infecciosa, no especificada', 'Infeccioso'),
('B37.9', 'Candidiasis, no especificada', 'Infeccioso'),
('B86', 'Escabiosis', 'Infeccioso'),
('A69.2', 'Enfermedad de Lyme', 'Infeccioso'),

-- INFECCIONES DEL TRACTO URINARIO
('N39.0', 'Infección de vías urinarias, sitio no especificado', 'Urológico'),
('N10', 'Nefritis tubulointersticial aguda (pielonefritis aguda)', 'Urológico'),
('N12', 'Nefritis tubulointersticial, no especificada como aguda o crónica', 'Urológico'),
('N30.0', 'Cistitis aguda', 'Urológico'),
('N30.9', 'Cistitis, no especificada', 'Urológico'),
('N34.1', 'Uretritis inespecífica', 'Urológico'),

-- ENFERMEDADES NEUROLÓGICAS
('G03.9', 'Meningitis, no especificada', 'Neurológico'),
('G00.9', 'Meningitis bacteriana, no especificada', 'Neurológico'),
('G02.0', 'Meningitis en enfermedades virales clasificadas en otra parte', 'Neurológico'),
('G04.9', 'Encefalitis, mielitis y encefalomielitis, no especificadas', 'Neurológico'),
('G04.0', 'Encefalitis aguda diseminada', 'Neurológico'),
('G04.2', 'Meningoencefalitis y meningomielitis bacterianas, no clasificadas en otra parte', 'Neurológico'),
('G05.1', 'Encefalitis, mielitis y encefalomielitis en enfermedades virales clasificadas en otra parte', 'Neurológico'),
('G40.9', 'Epilepsia, no especificada', 'Neurológico'),
('G40.0', 'Epilepsia y síndromes epilépticos idiopáticos relacionados con localizaciones (focales) (parciales) y con ataques de inicio localizado', 'Neurológico'),
('G40.1', 'Epilepsia y síndromes epilépticos sintomáticos relacionados con localizaciones (focales) (parciales) y con ataques parciales simples', 'Neurológico'),
('G40.3', 'Epilepsia y síndromes epilépticos generalizados idiopáticos', 'Neurológico'),
('G41.9', 'Estado epiléptico, no especificado', 'Neurológico'),
('G41.0', 'Estado de gran mal epiléptico', 'Neurológico'),
('R56.0', 'Convulsiones febriles', 'Neurológico'),
('R56.8', 'Otras convulsiones y las no especificadas', 'Neurológico'),
('G93.6', 'Edema cerebral', 'Neurológico'),
('G93.5', 'Compresión del encéfalo', 'Neurológico'),
('G91.9', 'Hidrocefalia, no especificada', 'Neurológico'),

-- ENFERMEDADES GASTROINTESTINALES
('K52.9', 'Gastroenteritis y colitis no infecciosas, no especificadas', 'Gastrointestinal'),
('K59.0', 'Constipación', 'Gastrointestinal'),
('K59.1', 'Diarrea funcional', 'Gastrointestinal'),
('K21.9', 'Enfermedad por reflujo gastroesofágico sin esofagitis', 'Gastrointestinal'),
('K21.0', 'Enfermedad por reflujo gastroesofágico con esofagitis', 'Gastrointestinal'),
('K29.7', 'Gastritis, no especificada', 'Gastrointestinal'),
('K35.8', 'Apendicitis aguda, no especificada', 'Gastrointestinal'),
('K40.9', 'Hernia inguinal unilateral o no especificada, sin obstrucción ni gangrena', 'Gastrointestinal'),
('K42.9', 'Hernia umbilical sin obstrucción ni gangrena', 'Gastrointestinal'),
('K56.0', 'Íleo paralítico', 'Gastrointestinal'),
('K56.6', 'Otras obstrucciones intestinales y las no especificadas', 'Gastrointestinal'),
('K80.2', 'Cálculo de la vesícula biliar sin colecistitis', 'Gastrointestinal'),
('K81.0', 'Colecistitis aguda', 'Gastrointestinal'),

-- ENFERMEDADES DERMATOLÓGICAS
('L20.9', 'Dermatitis atópica, no especificada', 'Dermatológico'),
('L21.9', 'Dermatitis seborreica, no especificada', 'Dermatológico'),
('L22', 'Dermatitis del pañal', 'Dermatológico'),
('L23.9', 'Dermatitis alérgica de contacto, de causa no especificada', 'Dermatológico'),
('L30.9', 'Dermatitis, no especificada', 'Dermatológico'),
('L50.9', 'Urticaria, no especificada', 'Dermatológico'),
('L03.9', 'Celulitis, de sitio no especificado', 'Dermatológico'),
('L01.0', 'Impétigo (cualquier sitio) (cualquier organismo)', 'Dermatológico'),
('L02.9', 'Absceso cutáneo, furúnculo y carbunco de sitio no especificado', 'Dermatológico'),
('L08.9', 'Infección local de la piel y del tejido subcutáneo, no especificada', 'Dermatológico'),

-- ENFERMEDADES HEMATOLÓGICAS
('D50.9', 'Anemia por deficiencia de hierro, sin otra especificación', 'Hematológico'),
('D50.0', 'Anemia por deficiencia de hierro secundaria a pérdida de sangre (crónica)', 'Hematológico'),
('D51.9', 'Anemia por deficiencia de vitamina B12, sin otra especificación', 'Hematológico'),
('D52.9', 'Anemia por deficiencia de folato, sin otra especificación', 'Hematológico'),
('D53.9', 'Anemia nutricional, sin otra especificación', 'Hematológico'),
('D64.9', 'Anemia, no especificada', 'Hematológico'),
('D69.6', 'Trombocitopenia, no especificada', 'Hematológico'),
('D69.3', 'Púrpura trombocitopénica idiopática', 'Hematológico'),
('D68.9', 'Trastorno de la coagulación, no especificado', 'Hematológico'),
('D66', 'Deficiencia hereditaria del factor VIII (Hemofilia A)', 'Hematológico'),
('D67', 'Deficiencia hereditaria del factor IX (Hemofilia B)', 'Hematológico'),
('D57.1', 'Enfermedad de células falciformes sin crisis', 'Hematológico'),

-- ENFERMEDADES METABÓLICAS Y ENDOCRINAS
('E86.0', 'Deshidratación', 'Metabólico'),
('E87.1', 'Hiposmolalidad e hiponatremia', 'Metabólico'),
('E87.0', 'Hiperosmolalidad e hipernatremia', 'Metabólico'),
('E87.5', 'Hiperpotasemia', 'Metabólico'),
('E87.6', 'Hipopotasemia', 'Metabólico'),
('E87.2', 'Acidosis', 'Metabólico'),
('E87.3', 'Alcalosis', 'Metabólico'),
('E10.9', 'Diabetes mellitus insulinodependiente sin mención de complicación', 'Metabólico'),
('E11.9', 'Diabetes mellitus no insulinodependiente sin mención de complicación', 'Metabólico'),
('E16.2', 'Hipoglucemia, no especificada', 'Metabólico'),
('E03.9', 'Hipotiroidismo, no especificado', 'Metabólico'),
('E05.9', 'Tirotoxicosis, no especificada', 'Metabólico'),
('E55.9', 'Deficiencia de vitamina D, no especificada', 'Metabólico'),
('E66.9', 'Obesidad, no especificada', 'Metabólico'),
('E44.0', 'Desnutrición proteicocalórica moderada', 'Metabólico'),
('E44.1', 'Desnutrición proteicocalórica leve', 'Metabólico'),
('E46', 'Desnutrición proteicocalórica, no especificada', 'Metabólico'),

-- ENFERMEDADES CARDIOVASCULARES
('I51.9', 'Enfermedad cardíaca, no especificada', 'Cardiovascular'),
('I50.9', 'Insuficiencia cardíaca, no especificada', 'Cardiovascular'),
('I47.1', 'Taquicardia supraventricular', 'Cardiovascular'),
('I47.2', 'Taquicardia ventricular', 'Cardiovascular'),
('I49.9', 'Arritmia cardíaca, no especificada', 'Cardiovascular'),
('Q21.0', 'Defecto del tabique ventricular', 'Cardiovascular'),
('Q21.1', 'Defecto del tabique auricular', 'Cardiovascular'),
('Q25.0', 'Conducto arterioso permeable', 'Cardiovascular'),
('I10', 'Hipertensión esencial (primaria)', 'Cardiovascular'),
('I95.9', 'Hipotensión, no especificada', 'Cardiovascular'),

-- ENFERMEDADES RENALES
('N17.9', 'Insuficiencia renal aguda, no especificada', 'Renal'),
('N18.9', 'Enfermedad renal crónica, no especificada', 'Renal'),
('N04.9', 'Síndrome nefrótico, anomalía morfológica no especificada', 'Renal'),
('N05.9', 'Síndrome nefrítico no especificado', 'Renal'),

-- TRAUMATISMOS Y ENVENENAMIENTOS
('S06.9', 'Traumatismo intracraneal, no especificado', 'Traumatismo'),
('S06.0', 'Conmoción cerebral', 'Traumatismo'),
('T78.3', 'Edema angioneurótico', 'Alergia'),
('T78.4', 'Alergia no especificada', 'Alergia'),
('T78.2', 'Shock anafiláctico, no especificado', 'Alergia'),
('T88.6', 'Shock anafiláctico debido a efecto adverso de droga o medicamento correcto administrado apropiadamente', 'Alergia'),

-- SÍNTOMAS Y SIGNOS
('R50.9', 'Fiebre, no especificada', 'Síntoma'),
('R51', 'Cefalea', 'Síntoma'),
('R10.4', 'Otros dolores abdominales y los no especificados', 'Síntoma'),
('R11', 'Náusea y vómito', 'Síntoma'),
('R19.7', 'Diarrea, no especificada', 'Síntoma'),
('R05', 'Tos', 'Síntoma'),
('R06.0', 'Disnea', 'Síntoma'),
('R06.2', 'Sibilancias', 'Síntoma'),
('R06.8', 'Otras anomalías de la respiración y las no especificadas', 'Síntoma'),
('R21', 'Erupción y otras erupciones cutáneas inespecíficas', 'Síntoma'),
('R55', 'Síncope y colapso', 'Síntoma'),

-- CONDICIONES PERINATALES
('P22.0', 'Síndrome de dificultad respiratoria del recién nacido', 'Neonatal'),
('P22.9', 'Dificultad respiratoria del recién nacido, no especificada', 'Neonatal'),
('P59.9', 'Ictericia neonatal, no especificada', 'Neonatal'),
('P07.3', 'Otros recién nacidos de pretérmino', 'Neonatal'),
('P07.0', 'Peso extremadamente bajo al nacer', 'Neonatal'),
('P07.1', 'Otros pesos bajos al nacer', 'Neonatal'),
('P36.9', 'Sepsis bacteriana del recién nacido, no especificada', 'Neonatal'),
('P38', 'Onfalitis del recién nacido con o sin hemorragia leve', 'Neonatal'),

-- MALFORMACIONES CONGÉNITAS
('Q90.9', 'Síndrome de Down, no especificado', 'Congénito'),
('Q03.9', 'Hidrocéfalo congénito, no especificado', 'Congénito'),
('Q05.9', 'Espina bífida, no especificada', 'Congénito'),
('Q35.9', 'Fisura del paladar, no especificada', 'Congénito'),
('Q36.9', 'Labio leporino, no especificado', 'Congénito'),
('Q37.9', 'Fisura del paladar con labio leporino, no especificada', 'Congénito'),
('Q53.9', 'Testículo no descendido, no especificado', 'Congénito'),

-- OTROS DIAGNÓSTICOS PEDIÁTRICOS COMUNES
('K00.7', 'Síndrome de la erupción dentaria', 'Odontológico'),
('H10.9', 'Conjuntivitis, no especificada', 'Oftalmológico'),
('H66.9', 'Otitis media, no especificada', 'Otorrinolaringológico'),
('H66.0', 'Otitis media aguda supurativa', 'Otorrinolaringológico'),
('H65.9', 'Otitis media no supurativa, no especificada', 'Otorrinolaringológico'),
('J35.0', 'Amigdalitis crónica', 'Otorrinolaringológico'),
('J35.1', 'Hipertrofia de las amígdalas', 'Otorrinolaringológico'),
('J35.2', 'Hipertrofia de las adenoides', 'Otorrinolaringológico'),
('J35.3', 'Hipertrofia de las amígdalas con hipertrofia de las adenoides', 'Otorrinolaringológico'),
('R62.8', 'Otras fallas del desarrollo fisiológico normal esperado', 'Desarrollo'),
('R62.0', 'Falta del desarrollo fisiológico normal esperado', 'Desarrollo'),
('F90.0', 'Trastorno de la actividad y de la atención', 'Psiquiátrico'),
('F84.0', 'Autismo infantil', 'Psiquiátrico'),
('F80.9', 'Trastorno del desarrollo del habla y del lenguaje, no especificado', 'Psiquiátrico')

ON CONFLICT (code) DO UPDATE SET
  description = EXCLUDED.description,
  category = EXCLUDED.category;
