import {
  Loader2,
  FileSpreadsheet,
  FileText,
  Download,
  AlertCircle,
  CheckCircle,
  XCircle,
  Info,
  Search,
  X,
  Plus,
  Minus,
  Calendar,
  Clock,
  User,
  Users,
  Settings,
  LogOut,
  Home,
  FileText as File,
  Upload,
  Trash2,
  Edit,
  Eye,
  EyeOff,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  MoreVertical,
  MoreHorizontal,
  Filter,
  SortAsc,
  SortDesc,
  RefreshCw,
  Save,
  Copy,
  Clipboard,
  Check,
  AlertTriangle,
  Mail,
  Phone,
  MapPin,
  Star,
  Heart,
  Share2,
  Bookmark,
  Bell,
  BellOff,
  Menu,
  Grid,
  List,
  Layout,
  Maximize,
  Minimize,
  ZoomIn,
  ZoomOut,
  RotateCw,
  RotateCcw,
  Pencil,
  Activity,
  TrendingUp,
  TrendingDown,
  BarChart,
  PieChart,
  LineChart as Chart,
  Archive,
  Folder,
  FolderOpen,
  Printer,
  FileDown,
  FileUp,
  Link,
  ExternalLink,
  Paperclip,
  Image,
  Film,
  Music,
  Volume2,
  VolumeX,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Lock,
  Unlock,
  Shield,
  Key,
  HelpCircle,
  MessageCircle,
  MessageSquare,
  Send,
  ThumbsUp,
  ThumbsDown,
  Flag,
  Award,
  Target,
  Zap,
  Coffee,
  Briefcase,
  Package,
  ShoppingCart,
  ShoppingBag,
  CreditCard,
  DollarSign,
  Percent,
  Gift,
  Tag,
  Layers,
  Box,
  Database,
  Server,
  Cloud,
  CloudOff,
  Wifi,
  WifiOff,
  Bluetooth,
  Cast,
  Monitor,
  Smartphone,
  Tablet,
  Watch,
  Camera,
  Video,
  Mic,
  MicOff,
  Headphones,
  Speaker,
  Battery,
  BatteryCharging,
  Power,
  PowerOff,
  Sun,
  Moon,
  CloudRain,
  CloudSnow,
  Wind,
  Droplet,
  Thermometer,
  Compass,
  Navigation,
  Navigation2,
  Map,
  Globe,
  Anchor,
  Truck,
  Bus,
  Car,
  Bike,
  Plane,
  Train,
  Umbrella,
} from "lucide-react";

export const Icons = {
  spinner: Loader2,
  fileSpreadsheet: FileSpreadsheet,
  filePdf: FileText,
  fileText: FileText,
  download: Download,
  alertCircle: AlertCircle,
  checkCircle: CheckCircle,
  xCircle: XCircle,
  info: Info,
  search: Search,
  x: X,
  plus: Plus,
  minus: Minus,
  calendar: Calendar,
  clock: Clock,
  user: User,
  users: Users,
  settings: Settings,
  logOut: LogOut,
  home: Home,
  file: File,
  upload: Upload,
  trash: Trash2,
  trash2: Trash2,
  edit: Edit,
  pencil: Pencil,
  eye: Eye,
  eyeOff: EyeOff,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  moreVertical: MoreVertical,
  moreHorizontal: MoreHorizontal,
  filter: Filter,
  sortAsc: SortAsc,
  sortDesc: SortDesc,
  refreshCw: RefreshCw,
  save: Save,
  copy: Copy,
  clipboard: Clipboard,
  check: Check,
  alertTriangle: AlertTriangle,
  mail: Mail,
  phone: Phone,
  mapPin: MapPin,
  star: Star,
  heart: Heart,
  share2: Share2,
  bookmark: Bookmark,
  bell: Bell,
  bellOff: BellOff,
  menu: Menu,
  grid: Grid,
  list: List,
  layout: Layout,
  maximize: Maximize,
  minimize: Minimize,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  rotateCw: RotateCw,
  rotateCcw: RotateCcw,
  activity: Activity,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  barChart: BarChart,
  pieChart: PieChart,
  chart: Chart,
  archive: Archive,
  folder: Folder,
  folderOpen: FolderOpen,
  printer: Printer,
  fileDown: FileDown,
  fileUp: FileUp,
  link: Link,
  externalLink: ExternalLink,
  paperclip: Paperclip,
  image: Image,
  film: Film,
  music: Music,
  volume2: Volume2,
  volumeX: VolumeX,
  play: Play,
  pause: Pause,
  skipBack: SkipBack,
  skipForward: SkipForward,
  lock: Lock,
  unlock: Unlock,
  shield: Shield,
  key: Key,
  helpCircle: HelpCircle,
  messageCircle: MessageCircle,
  messageSquare: MessageSquare,
  send: Send,
  thumbsUp: ThumbsUp,
  thumbsDown: ThumbsDown,
  flag: Flag,
  award: Award,
  target: Target,
  zap: Zap,
  coffee: Coffee,
  briefcase: Briefcase,
  package: Package,
  shoppingCart: ShoppingCart,
  shoppingBag: ShoppingBag,
  creditCard: CreditCard,
  dollarSign: DollarSign,
  percent: Percent,
  gift: Gift,
  tag: Tag,
  layers: Layers,
  box: Box,
  database: Database,
  server: Server,
  cloud: Cloud,
  cloudOff: CloudOff,
  wifi: Wifi,
  wifiOff: WifiOff,
  bluetooth: Bluetooth,
  cast: Cast,
  monitor: Monitor,
  smartphone: Smartphone,
  tablet: Tablet,
  watch: Watch,
  camera: Camera,
  video: Video,
  mic: Mic,
  micOff: MicOff,
  headphones: Headphones,
  speaker: Speaker,
  battery: Battery,
  batteryCharging: BatteryCharging,
  power: Power,
  powerOff: PowerOff,
  sun: Sun,
  moon: Moon,
  cloudRain: CloudRain,
  cloudSnow: CloudSnow,
  wind: Wind,
  droplet: Droplet,
  thermometer: Thermometer,
  compass: Compass,
  navigation: Navigation,
  navigation2: Navigation2,
  map: Map,
  globe: Globe,
  anchor: Anchor,
  truck: Truck,
  bus: Bus,
  car: Car,
  bike: Bike,
  plane: Plane,
  train: Train,
  umbrella: Umbrella,
} as const;
